### ISSUE TITLE
No diagrams rendered since 3228

### ISSUE THREAD

**Issue by beffge** [structurizr/lite#100]
### Description

Since release 3228 the following errors show up in my chrome and the diagrams are not rendered anymore:
![image](https://github.com/structurizr/lite/assets/88820893/b7875819-62c4-4276-9398-d6cf268a3960)
 

### Steps to reproduce

1. take the json from https://www.structurizr.com/json and save it locally to a workspace.json
2. start structurizr lite as docker container
3. check chrome console log for errors

### Severity

Minor

### Priority

I have no budget and there's no rush, please fix this for free

**Comment by simonbrowndotje** [comment]
Perhaps a browser caching issue?

**Comment by beffge** [comment]
😭 sorry for the unnecessary issue
