### ISSUE TITLE
Documentation headings are rendered incorrectly

### ISSUE THREAD

**Issue by jeroenwo** [structurizr/lite#101]
### Description

For every .md file you add to the documentation, the first heading (regardless of it being #, ## or ###) is rendered as plain text.

### Steps to reproduce

1. Start structurizr example
2. Goto documentation
3. See the generated documentation
[structurizr-issue.zip](https://github.com/structurizr/lite/files/13399519/structurizr-issue.zip)

### Screenshot

![image](https://github.com/structurizr/lite/assets/13014081/d7c5a5e2-31e2-402c-b16a-1938266d698d)

### Severity

Minor

### Priority

I have no budget and there's no rush, please fix this for free

**Comment by simonbrowndotje** [comment]
The `.md` files were saved as UTF-8 with BOM, rather than just plain UTF-8, and the leading control character was throwing off the conversion to Markdown. Lite v3232 should resolve this.

**Comment by jeroenwo** [comment]
Check, it works!
