### ISSUE TITLE
Diagrams not rendered when using !includes only

### ISSUE THREAD

**Issue by yvesaston** [structurizr/lite#122]
### Description

- One "System A model.dsl" file, containing only the actual model definition of the system:
```
SystemA = softwareSystem "SystemA" "Example system A" "Base" {
    Container1 = container "Container 1" "Example container 1" "Tech 1" "Base"
    Container2 = container "Container 2" "Example container 2" "Tech 1" "Base"
    Container1 -> Container2 "Performs" "Library call"
}
```

- One "System A views.dsl" file, containing only the views definition for the system:

```
systemContext SystemA SystemAContext {
    include *
}

container SystemA SystemAContainer {
    include *
}
```

- One "System A.dsl" file, putting it all together:
```
workspace "System A" {
    !identifiers hierarchical

model {
    !include "System A model.dsl"
}

views {
    !include "System A views.dsl"
}
```

**Note**
The reason to separate a system Model and Views in different files that are included is to allow to reuse them.
System A being part of Domain D, and having the same model and views separated DSL files for System B, Domain D DSL would look like:
```
workspace "Domain D" {
    !identifiers hierarchical

    model {
        !include "System A model.dsl"
        !include "System B model.dsl"
    }

    views {
        systemLandscape domainD domainDLandscape {
            title "Domaain landscape"
            include *
        }
        !include "System A views.dsl"
        !include "System B views.dsl"
        !include "styles.dsl"
    }
}
```

### Steps to reproduce

1. Create 3 DSL files as exposed in the description (one for the model, one for the views and one for the workspace).
2. Run structurizr/lite Docker container, on the workspace DSL (aka SystemA.dsl)
3. open localhost in Chrome
4. No error provided, yet the rendering of the workspace is not the expected one.

### Screenshot

![Structurizr lite multi-DSL bug](https://github.com/structurizr/lite/assets/123368955/522f5d4e-8e39-4c3a-898c-601057a81f6d)

### Severity

Minor

### Priority

I have no budget and there's no rush, please fix this for free

### More information

Structurizr/lite 2024.03.03 (on JDK 21.0.1).

**Comment by simonbrowndotje** [comment]
It works for me ... I suspect the command you're using to start Lite is incorrect.
