### ISSUE TITLE
Generated offline HTML Export not zoomable

### ISSUE THREAD

**Issue by pkunze** [structurizr/lite#13]
First of all: I love the approach! Awesome tool!

I just bumped into an issue (quite possible that I am not seeing some option).
The Generated offline HTML Page is not zoomable.

This makes Diagrams with 2 vertically "stacked" elements huge. 

Is there some way to either fit the diagrams to the viewport or make them zoomable?

**Comment by simonbrowndotje** [comment]
Thanks for the kind words. That's correct, the offline HTML export has a limited amount of JavaScript, and isn't zoomable I'm afraid. If you need the interactive/zoomable diagrams, I'd recommend asking people to start up Structurizr Lite (free), or to publish the diagrams via the on-premises installation (also free).

**Comment by simonbrowndotje** [comment]
Something you could do is increase the page size of specific diagrams, which would add some padding around the elements, making them rendered smaller in the resulting HTML page. You will need to disable automatic layout for that view if it's enabled.

**Comment by pkunze** [comment]
Fair enough. I still see this as a valuable feature for future releases, since I would be willing to share the export with clients when discussing changes etc, but your comments already helped me. 👍

Feel free to close this issue or leave it open if you consider adding the functionality in the future. :)
