### ISSUE TITLE
Structurizr overwrites manual allocation of the elements

### ISSUE THREAD

**Issue by OlegKunitsyn** [structurizr/lite#130]
### Description

Views with manual layouts overwritten in `structurizr.editable=false` mode, anyway. There should be a way to make workspace.json really read-only.
Update: Structurizr resets allocations of the elements in the named views voiding the hours of work. It's a bug IMO.

### Priority

I have no budget and there's no rush, please add this feature for free

### More information

![image](https://github.com/structurizr/lite/assets/2870028/92180e5f-bf5d-4c06-95e7-30b6105e0b7c)

**Comment by OlegKunitsyn** [comment]
Workaround for docker compose:  `:ro` flag mounting the folder
Workaround for K8S: set `444` permissions on workspace.json

**Comment by simonbrowndotje** [comment]
The file system needs to be writeable - Lite parses the DSL file to create the JSON file, with `structurizr.editable=false` making the diagrams non-editable from the UI. I think you're running into a different issue, but I'm unable to reproduce it given the limited information provided unfortunately.

**Comment by OlegKunitsyn** [comment]
Non-editable diagrams should be non-editable completely. ATM the embedding via iframe overwrites diagrams.

**Comment by simonbrowndotje** [comment]
Embedding diagrams via an iframe isn't supported by Lite, so I'd recommend using the on-premises installation instead -> https://docs.structurizr.com/onpremises/embed#iframe-embed

**Comment by OlegKunitsyn** [comment]
I see the business points, with full respect.

For the community. EmbedController has 2 endpoints for embedding. The Lite can be deployed in the Intranet and integrated with Confluence using iframe and `/workspace/embed` endpoint.

**Comment by simonbrowndotje** [comment]
> I see the business points, with full respect.
> For the community.

The on-premises installation is free and open source too, with features specifically designed for embedding via an iframe -> https://github.com/structurizr/onpremises
