### ISSUE TITLE
when using any version greater than 3216, it doesn't render diagrams

### ISSUE THREAD

**Issue by gilmardcom** [structurizr/lite#136]
### Question

Would anyone let me know if you have had the same issue, please?
<img width="1372" alt="Screenshot 2024-04-24 at 14 12 48" src="https://github.com/structurizr/lite/assets/97289578/13789d56-b460-466a-9296-951449825e48">

**Comment by gilmardcom** [comment]
btw, the generated JSON files are totally different between version 3216 and any later ones (like 'latest')

**Comment by simonbrowndotje** [comment]
Duplicate of #135
