### ISSUE TITLE
Unify configs for different deployments

### ISSUE THREAD

**Issue by OlegKunitsyn** [structurizr/lite#137]
### Description

Spring Boot has application.properties file designed to control the application without recompilation. Moreover, the values in application.properties can be overridden for different deployments without touching the filesystem/image - `structurizr.editable=false` for the publishing and `structurizr.editable=true` for editing.
structurizr.properties configuration file is excessive, and can be integrated into application.properties using the namespace `structurizr.` 

### Priority

I have no budget and there's no rush, please add this feature for free

**Comment by simonbrowndotje** [comment]
The idea here is that the `structurizr.properties` file sits next to the `workspace.dsl` file, so you can have different Lite configurations for different folders/workspaces. I'm not sure I see the value in pushing that configuration to the Spring Boot configuration file.
