### ISSUE TITLE
Add support for local theme files

### ISSUE THREAD

**Issue by wsaeed** [structurizr/lite#14]
Currently, themes only support URLs for downloading the themes file. Sometimes due to security and privacy, uploading these files to a public web server is impossible.

Add support for themes files stored in the data directory.

`themes https://static.structurizr.com/themes/microsoft-azure-2021.01.26/theme.json ./theme.json`

**Comment by wsaeed** [comment]
Adding a web server and keeping the theme files inside GitHub for versioning requires much more effort. We need to set up a publishing mechanism.

Structurizr lite is already using a web server to serve the diagrams. Can the theme files (JSON) be served via the web server?

**Comment by simonbrowndotje** [comment]
I'd like to understand your use case before adding such a facility ... theme files are designed to be hosted centrally for sharing across multiple workspaces, but it sounds like you're trying to do something different here?
