### ISSUE TITLE
Be able to raise an instance only for view C4 models

### ISSUE THREAD

**Issue by claudiovianatech** [structurizr/lite#16]
**First:**
Congratulations for the system, it's really great to use a tool that has a well-defined purpose and for which it is perfectly suited.

**The issue:**
The business areas should be able to visualize the models without being able to manipulate them.

Could be implemented a parameter in the instance configuration that blocks editing actions on the interface in all views, hiding the buttons, similar to what happens when the view uses autolayout?

Eg: structurizr.readOnly
In order not to affect the default behavior of the application, the default value could be equal to false

**Finally:**
I'm sure that a lot of people who use Structurizr would like to be able to contribute by coding, are there any plans to allow other devs to participate more actively in the project?

Thank you very much

**Comment by simonbrowndotje** [comment]
This is now available with a property named `structurizr.editable`; see https://structurizr.com/share/76352/documentation#read-only-diagrams for more.

> I'm sure that a lot of people who use Structurizr would like to be able to contribute by coding, are there any plans to allow other devs to participate more actively in the project?

All being well, Structurizr Lite will be open sourced later this year.
