### ISSUE TITLE
Stuck loading workspace with 2024-09-19 version

### ISSUE THREAD

**Issue by jan93** [structurizr/lite#162]
### Expected

I expect to be able to start the workspace in the same way as in the previous version, 2024-07-02.

### Actual

I am able to start the workspace in 2024-07-02, but doing the same procedure in 2024-09-19 version does not seem to complete loading the workspace, just hangs/is stuck.

### Steps to reproduce

**Steps:**

- Put "workspace.dsl" file in an empty folder
- Run old version 2024-07-02 and go to localhost:8080 to verify that workspace was loaded successfully    
```
docker run -it --rm -p 8080:8080 -v <full-path-to-folder>:/usr/local/structurizr structurizr/lite:2024.07.02
```
- Delete ".structurizr" folder and the "workspace.json" file
- Run new version 2024-09-19 and go to localhost:8080. Notice how the workspace is stuck loading.
```
docker run -it --rm -p 8080:8080 -v <full-path-to-folder>:/usr/local/structurizr structurizr/lite:2024.09.19
```

**Workspace.dsl file used:**
workspace {

    model {
        u = person "User"
        system = softwareSystem "Software System" {
            wa = container "Web Application" {
                tags "Application"
            }
            db = container "Database Schema" {
                tags "Database"
            }
        }

        u -> wa "Uses"
        wa -> db "Reads from"
    }

    views {
        systemContext system "Diagram1" {
            include *
            autolayout lr
        }

        container system "Diagram2" {
            include "->wa->"
            autolayout lr
        }

        styles {
            element "Element" {
                color white
            }
            element "Software System" {
                background #1DACD6
            }
            element "Person" {
                background #E5D3D3
                shape person
            }
            element "Database" {
                shape cylinder
                background #A39193
            }
            element "Application" {
                background #7C0A02
            }
        }
    }
    
}

### Version/build information

Using Structurizr docker version as listed here, 2024.09.19 and 2024.07.02.
https://hub.docker.com/r/structurizr/lite/tags

It's the first time I'm trying the newer version from today.

Note im using Docker API "dockerd (moby)" from Rancher Desktop version 1.14.1 which has a docker cli.

### Severity

Major

### Priority

I have no budget and there's no rush, please fix this for free

### More information

Was following this guide:
https://docs.structurizr.com/dsl/tutorial

See video below, reproducing the issue:

https://github.com/user-attachments/assets/a26566ad-ef09-495d-9c9d-361e3fcdcc9c

**Comment by jan93** [comment]
I see these errors. Issue with using dark mode?
```
structurizr.ui.initDarkMode is not a function
structurizr.ui.isDarkMode is not a function
GET http://localhost:8080/workspace/1/images/Diagram1-thumbnail.png 404 (Not Found)
GET http://localhost:8080/workspace/1/images/Diagram2-thumbnail.png 404 (Not Found)
```
![image](https://github.com/user-attachments/assets/eb5d766c-11a1-4833-bdc2-b644f1f298c2)

**Comment by simonbrowndotje** [comment]
Try doing a hard refresh in your web browser - something is likely being cached.

**Comment by jan93** [comment]
Tried from incognito window, seems to load now, so must have been something cached yes.
