### ISSUE TITLE
Host images from Lite

### ISSUE THREAD

**Issue by simonbrowndotje** [structurizr/lite#165]
### Description

See https://github.com/structurizr/lite/discussions/164

## Single workspace mode

Allow images in `{structurizrDataDirectory}/images` to be available via `http://localhost:8080/workspace/images`

## Multi-workspace mode

Allow images in `{structurizrDataDirectory}/{workspaceId}/images` to be available via `http://localhost:8080/workspace/{workspaceId}/images`

### Priority

I'm willing to add this feature myself and raise a PR (please confirm approach first)

**Comment by judgedim** [comment]
@simonbrowndotjeI have tested your changes related to this issue, and the solution works well (I added a small PR to make it a bit more flexible). Do you have any objections if I open the same issue for https://github.com/structurizr/onpremises ?

**Comment by simonbrowndotje** [comment]
Switching `{filename}` to `{*filename}` seems to permit sub-directories ... see https://github.com/structurizr/lite/commit/8f82aa4f9971197540addcaf6c8e748bf75272d3

Feel free to open an issue for the on-premises installation, but adding the same functionality requires some additional thought ... most users will not have direct access to the file system (or blob store) sitting behind the installation, and there's no way to upload arbitrary images at the moment.

**Comment by judgedim** [comment]
Yeah, `{*filename}` works . Thank you
