### ISSUE TITLE
Structurizr lite 3.0 - manual layout no operational

### ISSUE THREAD

**Issue by yvesaston** [structurizr/lite#166]
### Expected

Hi,

After upgrading to Structuizr Lite 3.0, manual layout is not operational anymore:

- it doesn't save the layout (nor the thumbnail),
- the alignment buttons are never enabled after selecting elements to align - both verticals and horizontals.

On an up-to-date Chrome, there is a big gray gap between the buttons area at the top and the actual diagramming area ; it doesn't happen on Microsoft Edge:
![Structurizr lite 3 0 buggy screenshot](https://github.com/user-attachments/assets/acb81305-256e-4f52-b6c6-6fc866ba5521)

### Actual

See Expected

### Steps to reproduce

Open a DSL with views w/o. autolayout set.

### Version/build information

Structurizr Lite
- build: 2024.09.19 (2024-09-19T10:42:00Z)
- structurizr-java: v3.0.0
- structurizr-dsl: v3.0.0
- structurizr-import: v3.0.0
- structurizr-graphviz: v3.0.0

### Severity

Major

### Priority

I have no budget and there's no rush, please fix this for free

**Comment by simonbrowndotje** [comment]
I use Chrome for development and demos, and it's working fine for me. I suspect this is a problem with your environment or there's something in your workspace that is causing an issue. I would recommend:

- Clearing your web browser's cache.
- Starting Lite up against an empty folder so it creates the example, to see if that works.
