### ISSUE TITLE
AsciiDoc preview doesn't hold the right order of Headings

### ISSUE THREAD

**Issue by temurchichua** [structurizr/lite#20]
Hey,

Preview of my `.adoc` file doesn't hold the right order of the headings. There is only one level 2 headings and every other level 3 heading is appended to that one. 

This is my  doc file:
![image](https://user-images.githubusercontent.com/69351709/214562545-0f77e20c-277e-4a86-abe2-dda293161253.png)

This is how it looks in Structurizrz lite:
![image](https://user-images.githubusercontent.com/69351709/214562762-bd3b56d2-8ec1-47c4-a89f-9ba4d0ad74c0.png)

Is it a bug or am I doing something wrong?

**Comment by simonbrowndotje** [comment]
Each section (designated by a level 2 heading) needs to be in a separate file, so you need to split the file at `== Components`. See https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#documentation for more.

**Comment by temurchichua** [comment]
I've structured each of the level 2 headings in independent files starting with corresponding `== Component name` like this:
![image](https://user-images.githubusercontent.com/69351709/214572885-7e25907e-dd18-4f46-9602-852bed546a55.png)
and it works like a charm:
![image](https://user-images.githubusercontent.com/69351709/214573005-7cfd258c-3647-4851-8664-bef1b83dc162.png)
Thanks for all your help @simonbrowndotje !
