### ISSUE TITLE
"Hide this introduction" checkbox doesn't work

### ISSUE THREAD

**Issue by max-arshinov** [structurizr/lite#21]
## Steps
1. Run structurizr lite in docker
2. Check the "Hide this introduction" checkbox and click "Close"
3. Refresh the page

## Expected
Popup doesn't show

## Actual
The popup shows regardless of the checkbox

<img width="897" alt="image" src="https://user-images.githubusercontent.com/820550/215591185-b3c834a3-d0f7-4232-8273-37f39e35f3a1.png">

**Comment by simonbrowndotje** [comment]
Duplicate of #17 and #15.
