### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by JoBa-BJSS** [structurizr/lite#41]
Hello,

Thanks for the effort that goes into maintaining + updating this project. We've been using the docker images to keep all our project docs together and it's been working great!

In the latest docker images it seems that we can't load ADRs or documentation though unfortunately.

If we peg the image tag to 3000 it seems to work great. 3001 throws an error in the console (but still appears to work) and 3002 doesn't load the ADRs & Documentation at all.

We have pegged our container image to 3000 and thats helped us continue for now, so I'm raising for awareness!

Thanks again

**Comment by JoBa-BJSS** [comment]
Heres the stack trace:
```
TypeError: Cannot read properties of undefined (reading 'length')
    at decisions:579:67
    at Array.forEach (<anonymous>)
    at decisions:578:46
    at Array.forEach (<anonymous>)
    at decisions:566:43
    at Array.forEach (<anonymous>)
    at init (decisions:554:53)
    at workspaceLoaded (decisions:512:13)
    at loadWorkspace (decisions:63:13)
    at decisions:1699:21
```

**Comment by simonbrowndotje** [comment]
`3004` is now available.

**Comment by simonbrowndotje** [comment]
I don't think there have been any changes to that file since the fix (https://github.com/structurizr/ui/commits/c1d7edf3505bed8d987ca1a6f917732d8f445be7/src/js/structurizr-workspace.js), so feel free to open a new issue with an example I can use to reproduce it.
