### ISSUE TITLE
Label 'latest' missing from dockerhub

### ISSUE THREAD

**Issue by roosemberth** [structurizr/lite#42]
Following the [_getting started_ guide](https://structurizr.com/share/76352/documentation) via the prebuild image yields the following error:

```
$ docker pull structurizr/lite
Using default tag: latest
Error response from daemon: manifest for structurizr/lite:latest not found: manifest unknown: manifest unknown
```

**Comment by simonbrowndotje** [comment]
`latest` has been removed temporarily because build 3002 was faulty ... `docker pull structurizr/lite:3000` should work though.

**Comment by simonbrowndotje** [comment]
It's back.
