### ISSUE TITLE
Feature Request: Realtime workspace editing

### ISSUE THREAD

**Issue by jeffabailey** [structurizr/lite#7]
Instead of making users reload Structurizer to see file changes in Structurizr Lite, update the workspace view immediately after files change.

In other words, remove [step six in the Structurizr lite workflow](https://structurizr.com/help/lite/workflow#:~:text=the%20new%20workspace-,refresh%20your%20web%20browser%20to%20see%20the%20changes.,-To%20publish%20your).

**Comment by simonbrowndotje** [comment]
This is now available; see https://structurizr.com/share/76352/documentation/Structurizr%20Lite#auto-refresh for details.

**Comment by ibayer** [comment]
@jeffabailey 

Thanks for making structurizr-lite available. This gives me a seconds changes to try out the 4c model. Last time I gave up quickly after drawing some diagram manually and trying C4-PlantUML.

>  * excluding on-premises installations with self-signed certificates; support for this may be added in the future 

source: [1]

I'm trying out structurizr light via a local docker run as described in [0]. Is the auto-refresh feature expected to work in this setting?

Again from [0]

> If you make a change to the DSL file and save it, you should see that change immediately reflected when you refresh your web browser.

I expected that auto-refresh would work out of the box, but this doesn't seem the case for me. Manual browser page reloading works, but this makes the editing workflow much less exciting.

```
2022-12-20 10:16:46.704  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : Structurizr Lite
2022-12-20 10:16:46.706  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : Build: 2876
2022-12-20 10:16:46.707  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : Built: 2022-11-24T13:07:43Z
2022-12-20 10:16:46.708  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : structurizr-java: v1.16.1
2022-12-20 10:16:46.720  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : structurizr-dsl: v1.21.0
```

- [0] https://dev.to/simonbrown/getting-started-with-structurizr-lite-27d0
- [1] https://structurizr.com/help/lite/sync

**Comment by simonbrowndotje** [comment]
The docs link has moved, and is available at https://structurizr.com/share/76352/documentation#auto-refresh instead.

**Comment by simonbrowndotje** [comment]
You're welcome. The [docs](https://structurizr.com/share/76352/documentation#usage) (linked to from https://structurizr.com/help/lite) does state the following:

> Navigating to http://localhost:8080/ should open Structurizr Lite, where you'll be able to view any diagrams, documentation, and decision records defined in your workspace. Any changes made to the workspace.dsl or workspace.json files will be reflected when you refresh your web browser.

Feel free to make a PR if you think the docs can be improved. The docs source is at https://github.com/structurizr/lite/blob/main/docs/docs/03-usage.md
