### ISSUE TITLE
Generated HTML offline page is not clickable

### ISSUE THREAD

**Issue by renannprado** [structurizr/lite#8]
The title says it all, when you're inside of Structurizr Lite, you can click throughout the diagrams, but when you generate the offline HTML page, you don't have this option.

The mouse shows a (+) Zoom icon, however double clicking doesn't do anything.

**Comment by simonbrowndotje** [comment]
I've just tried this with the latest version of Structurizr Lite, and the export is clickable for me.

**Comment by renannprado** [comment]
@simonbrowndotje thanks for the reply. I'll try once more then and provide a reproducer if that's still the case.
