### ISSUE TITLE
Feature Request: Navigate to thumbnail on page reload

### ISSUE THREAD

**Issue by eugeneniemand** [structurizr/lite#9]
I have many views and thus a long list of thumbnails. When I make a change in the model and then subsequently reload the page to see the change, the correct diagram loads due to it being in the URL; However, the thumbnail list is defaulted with the first view at the top. Is it possible to scroll the thumbnail list to have the current diagram in view?

**Comment by simonbrowndotje** [comment]
This should be working better now.

**Comment by eugeneniemand** [comment]
Perfect, well done and thank you for the prompt delivery of features.
