### ISSUE TITLE
Bump up Java version from 17 to 21

### ISSUE THREAD

**Issue by bioform** [structurizr/lite#96]
### Description

It would be good to use the `Pattern Matching` feature of Java 21 in custom DSL plugins.

### Priority

Low

### Resolution

I'm willing to add this feature myself and raise a PR

**Comment by simonbrowndotje** [comment]
I'm guessing that you're referring to the pre-built Docker image?

**Comment by bioform** [comment]
yep
it's about the pre-built Docker image :slightly_smiling_face:

**Comment by bioform** [comment]
And it would be good to have the ability to use Virtual Threads as well. 
My plugin needs to deal with third-party services and its requests can be easily parallelized(to increase performance).
It is clear, that it is possible to use `ThreadPoolExecutor` for the same purpose, 
but virtual threads simplify code a bit, so... why not? :slightly_smiling_face:
